### ISSUE TITLE
XCode 7 complains: building for iOS simulator, but linking in object file built for OSX, for architecture x86_64

### ISSUE THREAD

**Issue by tamird** [TimNN/cargo-lipo#3] opened 2016-07-02 15:36 UTC
See https://github.com/google/j2objc/issues/611. Looks like the solution is to `lipo` macOS targets separately from iOS targets (that's what j2objc did: https://github.com/google/j2objc/commit/5be2b442600387b48bdc8c12b9b62e31df9240d1).

Bummer.

**Comment by TimNN** [comment] 2016-07-02 16:45
Hi, thanks for the report.

I could not reproduce the issue: I could successfully link to and call into a library build with `cargo-lipo` (with XCode 7.3.1, tested with iPhone 6S simulator, iPhone 4S simulator & an actual iPhone 6s).

Could you provide me with some more detailed steps on how to reproduce the XCode complaint?

Also, from reading the issue you linked, I believe that the problem should only apply to universal libraries which contains code for both macOS & iOS Simulator. The universal libraries produced by `cargo-lipo` however never contain code for macOS, they only contain code for the various iOS architectures.

**Comment by tamird** [comment] 2016-07-02 16:47
Perhaps I've done something wrong? The project in question is https://github.com/tamird/SwiftyBucket - opening that and running it in XCode 7.3.1 produces the warnings; can you try it locally?

**Comment by TimNN** [comment] 2016-07-02 17:03
I tried your project locally:

* I had to fix paths which were hardcoded to your user
* I had turn of the "Enable Bitcode" setting
* I had to manually invoke `cargo lipo` in the `rusty` directory

Afterwards your application build & ran without issues on an actual iPhone 6 & the iPhone 6 simulator:

![screen shot 2016-07-02 at 18 57 17](https://cloud.githubusercontent.com/assets/1178249/16541617/8f5a8e6e-4087-11e6-896b-cfcadbaac055.png)

**Comment by tamird** [comment] 2016-07-02 17:21
> I had to fix paths which were hardcoded to your user

Good call, pushed a commit to fix this.

> I had turn of the "Enable Bitcode" setting

How come?

> I had to manually invoke cargo lipo in the rusty directory (edit: since the cargo invocation as an external tool did not work).

Fixed this as well.

I thought maybe I had some cached state, so I ran `git clean -dxf` and recompiled (from xcode) and I still get these warnings.

<img width="1440" alt="screen shot 2016-07-02 at 13 20 05" src="https://cloud.githubusercontent.com/assets/1535036/16541692/ca8b3bda-4057-11e6-9ce6-ef7fb8b10305.png">

**Comment by TimNN** [comment] 2016-07-02 18:16
> > I had turn of the "Enable Bitcode" setting

> How come?

Because otherwise my build failed (this only happens when building for / running on the actual device, not the simulator targets).

Which rust version are you using (`rustc -vV`) (I'm using rust stable 1.9.0)?

Where did you install rust and the ios standard library from?

If I understand the linker error correctly, the problems are not directly with the library generated by rust but rather the `powidf2.c.o` and `powisf2.c.o` object files which end up in you binary (they are part of the `runtime-rt` library, which is part of llvm and required by rust libraries).

**Comment by TimNN** [comment] 2016-07-02 18:24
Also see rust-lang/rust#29664

**Comment by tamird** [comment] 2016-07-02 18:47
Ah, this doesn't happen on 1.9.0, but does on 1.11.0 nightly.

**Comment by TimNN** [comment] 2016-07-02 19:19
Alright, so the 2016-06-23 nightly still works, I currently suspect that this was caused by rust-lang/rust#34055. I'm now going to test the next nightly after that pr was merged.

**Comment by tamird** [comment] 2016-07-02 20:07
Thanks for tracking this down.

**Comment by TimNN** [comment] 2016-07-02 20:08
Reported as rust-lang/rust#34617

**Comment by TimNN** [comment] 2016-07-05 21:06
A patch which should fix this issue (rust-lang/rust#34647) has been merged into the rust project and should be included in the next nightly.

I'll keep this issue open until I can verify it has been fixed with an official nightly build.

**Comment by TimNN** [comment] 2016-07-07 14:15
@tamird: I can no longer reproduce this issue with the latest nightly, so I'm closing this issue now.

Should it still occur for you, or if you find any other problems, feel free to open another issue.

**Closed by TimNN** 2016-07-07 14:15 UTC
